<?php
$buildingIds = [
  // Dwellings
  'D_Dwelling',
  'D_SimpleDwelling1',
  // 'D_SimpleDwelling2',
  // 'D_MixedDwelling',
  // 'D_CoupleDwelling',
  // 'D_AdditionalDwelling',
  //
  // // Green buildings
  // 'G_CuddleRoom',
  // 'G_BreakfastRoom',
  // 'G_StubbleRoom',
  // 'G_WorkRoom',
  // 'G_GuestRoom',
  // 'G_OfficeRoom',
  // 'G_Carpenter',
  // 'G_StoneCarver',
  // 'G_Blacksmith',
  // 'G_Miner',
  // 'G_Builder',
  // 'G_Trader',
  // 'G_WoodSupplier',
  // 'G_StoneSupplier',
  // 'G_RubySupplier',
  // 'G_DogSchool',
  // 'G_Quarry',
  // 'G_Seam',
  // 'G_SlaughteringCave',
  // 'G_CookingCave',
  // 'G_WorkingCave',
  // 'G_MiningCave',
  // 'G_BreedingCave',
  // 'G_PeacefulCave',
  //
  // // Yellow Buildings
  // 'Y_WeavingParlor',
  // 'Y_MilkingParlor',
  // 'Y_StateParlor',
  // 'Y_HuntingParlor',
  // 'Y_BeerParlor',
  // 'Y_BlacksmithingParlor',
  // 'Y_StoneStorage',
  // 'Y_OreStorage',
  // 'Y_SparePartStorage',
  // 'Y_MainStorage',
  // 'Y_WeaponStorage',
  // 'Y_SuppliesStorage',
  // 'Y_BroomChamber',
  // 'Y_TreasureChamber',
  // 'Y_FoodChamber',
  // 'Y_PrayerChamber',
  // 'Y_WritingChamber',
  // 'Y_FodderChamber',
];
